# Basic options
title: Improve your R code
short_name: Improve your R code
developers: [J Shields E Hannon]
description: Develop your scripts ready for sharing.
n_sessions: 1
prereq: NA
url: https://uniexeterrse.github.io/improve-r-code

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate

exclude: ['*.Rmd']
