name: knit-rmarkdown
run-name: ${{ github.actor }} is knitting rmarkdown lessons into markdown
on: [push]
jobs:
  knit-rmarkdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Install packages
        run: |
          R -e 'install.packages("blogdown")'
    # Run R script
      - name: build
        run: Rscript R/build.R
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated Change
          
          # Optional commit user and author settings
          commit_user_name: ejh243 # defaults to "github-actions[bot]"
          commit_user_email: e.j.hannon@exeter.ac.uk # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

