name: knit-rmarkdown
run-name: ${{ github.actor }} is knitting rmarkdown lessons into markdown
on: [push]
jobs:
  knit-rmarkdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Install packages
        run: |
          R -e 'install.packages("blogdown")'
    # Run R script
      - name: build
        run: Rscript R/build.R
